"""Add weekly/monthly scheduled booleans to user model.

Revision ID: b79d98bc08b4
Revises: 39869f041a68
Create Date: 2018-06-03 11:44:35.504196

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b79d98bc08b4'
down_revision = '39869f041a68'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('monthly_scheduled', sa.Boolean(), nullable=True))
    op.add_column('user', sa.Column('weekly_scheduled', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'weekly_scheduled')
    op.drop_column('user', 'monthly_scheduled')
    # ### end Alembic commands ###
